### ISSUE TITLE
Tag!

### ISSUE THREAD

**Issue by alex198555** [shine-jayakumar/insta-likecom-bot#1]
Hi!

How can I enable the script to like and comment by tag?! I tried but it doesn't work:

python instalikecombot.py bob101 b@bpassw0rd1 #haiku -ps "Follow me @bob101" -c mycomments.txt

PS C:\Users\aorek\Desktop\Python Bots\insta-likecom-bot-master\insta-likecom-bot-master> python instalikecombot.py bob101 b@bpassw0rd1 #haiku -ps "Follow me @bob101" -c mycomments.txt
usage: instalikecombot.py [-h] [-np NOOFPOSTS] [-ps TEXT] [-c FILE | -nc] [-d DELAY | -cz] username password target
instalikecombot: error: the following arguments are required: target
PS C:\Users\aorek\Desktop\Python Bots\insta-likecom-bot-master\insta-likecom-bot-master>

**Comment by shine-jayakumar** [comment]
The first 3 required parameters are: username, password, and target (in that order). If the parameters aren't separated with a space, you'd see such errors. I copied what you typed and it launches chrome and tries to login.

Also, the username (bob101) and password (b@bpassw0rd1) are used as examples. Use a valid username/password.

Please refer to the documentation.

Thank you.

**Comment by alex198555** [comment]
I mean if I type "#haiku" as the target, them the script is not executed and the web browser doesn't go through the posts of the mentioned tag.

**Comment by shine-jayakumar** [comment]
Would you be able to get the error message you get? I just tested for the same tag (#haiku). It worked for me. I am using python 3 on a Windows 10

**Comment by alex198555** [comment]
Please, check on the below request: 

![2022-04-27 11_46_46-Window](https://user-images.githubusercontent.com/30124814/165468284-80712cdc-9158-4d7d-b536-f0bd9136c241.png)

**Comment by alex198555** [comment]
Oh. Thanks so much. This issue is fixed and it works.

**Comment by shine-jayakumar** [comment]
Glad to hear that. Thanks for reporting the issue. I will add this in the documentation for PowerShell users.

**Comment by alex198555** [comment]
You are welcome and many thanks for the prompt replies.
