### ISSUE TITLE
Is it possible to like&comment on followers of a target?

### ISSUE THREAD

**Issue by lotrlol** [shine-jayakumar/insta-likecom-bot#10]
Hey there! First of all i want to thank you for this amazing bot! I think right now this is the only one that works, well done!

However, I was wondering if it is possible to target followers of lets say "Elon Musk" and like&comment on their content.
I'm sure that it would increase the effectivity of the bot tremendously.

I hope to hear from you soon :)

**Comment by shine-jayakumar** [comment]
> you

Thank you very much @lotrlol That's a really good feature you suggested. This should be added soon in the upcoming release.

**Comment by lotrlol** [comment]
Looking forward to it!

**Comment by shine-jayakumar** [comment]
Updated master branch with v.2.0:
Enables script to extract followers of a target and like/comments on the follower's posts.
