### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by MattMan00** [shine-jayakumar/insta-likecom-bot#106]
Hi,
i can't run the scrip, i got this error, can you help?

PS C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master> python ilcbot.py -pr tsdp.json -lm limits.json
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\ilcbot.py", line 37, in <module>
    stats = Stats(profile.limits)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\modules\stats.py", line 53, in __init__
    self._init_statsmon()
  File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\modules\stats.py", line 103, in _init_statsmon
    signal.signal(signal.SIGUSR1, handler=self._sighandler)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGUSR1'

**Comment by shine-jayakumar** [comment]
What is the OS and Python version?

**Comment by shine-jayakumar** [comment]
> Hi, i can't run the scrip, i got this error, can you help?
> 
> PS C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master> python ilcbot.py -pr tsdp.json -lm limits.json Traceback (most recent call last): File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\ilcbot.py", line 37, in stats = Stats(profile.limits) ^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\modules\stats.py", line 53, in **init** self._init_statsmon() File "C:\Users\Administrator\Documents\Scripts\insta-likecom-bot-master\modules\stats.py", line 103, in _init_statsmon signal.signal(signal.SIGUSR1, handler=self._sighandler) ^^^^^^^^^^^^^^ AttributeError: module 'signal' has no attribute 'SIGUSR1'

SIGUSR1 is not available on Window. For now, go to modules/stats.py, comment out  line #  53 (`self._init_statsmon()`).

I will include a permanent fix in the next update. Let me know if that works.

**Comment by shine-jayakumar** [comment]
Please get the latest version - 3.0.6
