### ISSUE TITLE
Do you have any delay on the code?

### ISSUE THREAD

**Issue by MehrnazAmoon** [shine-jayakumar/insta-likecom-bot#11]
Even I cant go further from the first stage :/

[*] => Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.
[*] => Total time taken: 4.4608 seconds

what I see in the Chrome is asking a question on the screen and dont allow me to answer that and it failed :/

**Comment by shine-jayakumar** [comment]
> Even I cant go further from the first stage :/
> 
> [_] => Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active. [_] => Total time taken: 4.4608 seconds
> 
> what I see in the Chrome is asking a question on the screen and dont allow me to answer that and it failed :/

Would you be able to share a screenshot of Chrome when you get this question?

**Comment by MehrnazAmoon** [comment]
yes sure
<img width="684" alt="Screenshot 2022-08-29 at 12 49 12" src="https://user-images.githubusercontent.com/62719906/187185071-8f8e9c59-031c-4fd8-ab16-e3300a07b067.png">

**Comment by MehrnazAmoon** [comment]
And even only one time I could accept Coockies and when its liking I got banned because its liking and commenting very fast without any delay and Instagram understand that its Bot not human, Add some delay between each activities 
<img width="419" alt="Screenshot 2022-08-29 at 12 52 11" src="https://user-images.githubusercontent.com/62719906/187185708-8b9b51f0-2c19-45b0-9402-97704ec5f421.png">

**Comment by shine-jayakumar** [comment]
> And even only one time I could accept Coockies and when its liking I got banned because its liking and commenting very fast without any delay and Instagram understand that its Bot not human, Suggesting to add some delay between each activities <img alt="Screenshot 2022-08-29 at 12 52 11" width="419" src="https://user-images.githubusercontent.com/62719906/187185708-8b9b51f0-2c19-45b0-9402-97704ec5f421.png">

If you don't specify a delay then it would wait randomly chooses a delay. The cookies dialogue box isn't handled in the script. You could also try a different browser - firefox is also supported.

**Comment by MehrnazAmoon** [comment]
You mean that I can add delay by myself? Ofcourse I can just wanted to improve your code. But there is no random delay on your code.

**Comment by shinejayakumar-nmg** [comment]
> You mean that I can add delay by myself? Ofcourse I can just wanted to improve your code. But there is no random delay on your code.

There's a random delay already added if the user doesn't specify a delay.
Check instalikecomboy.py line # 260  `delay = DELAY or randint(1,10)`

Also, user can provide a fixed delay using --delay option through command line.
