### ISSUE TITLE
Not working on windows? 

### ISSUE THREAD

**Issue by Jackiiiii** [shine-jayakumar/insta-likecom-bot#112]
is it made for windows too?

Traceback (most recent call last):
  File "D:\Bot\insta-likecom-bot-master\ilcbot.py", line 37, in <module>
    stats = Stats(profile.limits)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bot\insta-likecom-bot-master\modules\stats.py", line 53, in __init__
    self._init_statsmon()
  File "D:\Bot\insta-likecom-bot-master\modules\stats.py", line 103, in _init_statsmon
    signal.signal(signal.SIGUSR1, handler=self._sighandler)
                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGUSR1

**Comment by Jackiiiii** [comment]
I try to change the SIGUSR1, well didnt really work. browser open and then close. If use a directly like to my broweser profil its open but dont understand that i m already logged in.

**Comment by Jackiiiii** [comment]
[*] => [launch_insta]: Attempt - 1
[*] => Checking if user is already logged in
[*] => [Attempt# 1] Validating login
[*] => Failed to validate login
[*] => [Attempt# 2] Validating login
[*] => Failed to validate login
[*] => [Attempt# 3] Validating login
[*] => Failed to validate login
[*] => User not logged in. Attempting to login
[*] => Script ended with error
[*] => Error: [LoginFailedError] - Failed to login to Instagram

**Comment by shine-jayakumar** [comment]
Issue addressed in latest version v.3.0.5.
