### ISSUE TITLE
Fresh ubuntu install, all installed, still not working

### ISSUE THREAD

**Issue by lucasrhb** [shine-jayakumar/insta-likecom-bot#12]
Hello. That is what I have. Ubuntu 20.04 with all updates. Can you tell me where the problem is?

     ___ _  _ ___ _____ _      _    ___ _  _____ ___ ___  __  __     ___  ___ _____ 
    |_ _| \| / __|_   _/_\ ___| |  |_ _| |/ | __/ __/ _ \|  \/  |___| _ )/ _ |_   _|
     | || .` \__ \ | |/ _ |___| |__ | || ' <| _| (_| (_) | |\/| |___| _ | (_) || |  
    |___|_|\_|___/ |_/_/ \_\  |____|___|_|\_|___\___\___/|_|  |_|   |___/\___/ |_|  
    
    insta-likecom-bot v.1.4
    Automates likes and comments on an instagram account or tag

    Author: Shine Jayakumar
    Github: https://github.com/shine-jayakumar
    
    
[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Script ended with error : Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5638624ed403 <unknown>
#1 0x5638622f3778 <unknown>
#2 0x563862317fa9 <unknown>
#3 0x56386231312b <unknown>
#4 0x56386234e83a <unknown>
#5 0x5638623488f3 <unknown>
#6 0x56386231e0d8 <unknown>
#7 0x56386231f205 <unknown>
#8 0x563862534e3d <unknown>
#9 0x563862537db6 <unknown>
#10 0x56386251e13e <unknown>
#11 0x5638625389b5 <unknown>
#12 0x563862512970 <unknown>
#13 0x563862555228 <unknown>
#14 0x5638625553bf <unknown>
#15 0x56386256fabe <unknown>
#16 0x7faa164c6609 <unknown>

Traceback (most recent call last):
  File "instalikecombot.py", line 274, in <module>
    insta.quit()
AttributeError: 'NoneType' object has no attribute 'quit'

**Comment by shine-jayakumar** [comment]
Added `--disable-dev-shm-usage` for linux as per this article: [WebDriverException: unknown error: DevToolsActivePort file doesn't exist while trying to initiate Chrome Browser](https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t)

Created branch issue_12. Clone this branch and let me know if it works. It will be merged later. Also, run the script as a normal user and not a root user (as per the above article).
