### ISSUE TITLE
Closes Immediately 

### ISSUE THREAD

**Issue by SakaDiscord** [shine-jayakumar/insta-likecom-bot#13]
I need help, i dont know how to solve following errors: 
 
 ![unknown](https://user-images.githubusercontent.com/107799072/188915242-6101692b-5ba1-422f-a781-bb29715b1743.png)

**Comment by shinejayakumar-nmg** [comment]
Added python-dotenv to requirements.txt. You can create a virtual environment and install packages in requirements.txt
pip install -r requirements.txt
