### ISSUE TITLE
Won't go past "Save your login info?"

### ISSUE THREAD

**Issue by ghost** [shine-jayakumar/insta-likecom-bot#16]
Hi,

Thanks for making this.
It's been working flawlessly since I started using it a few weeks ago.
This morning when I tried using it, it can not seem to get past the save your login info screen "popup".

I get this error in the command prompt.

`[*] => Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.
Traceback (most recent call last):`

And here is a screenshot of the popup at login.

I have not changed anything account wise.

![Screenshot 2022-10-28 121912](https://user-images.githubusercontent.com/5818429/198716851-0f23f86d-fcd0-4db4-8ab6-1101e0e0fa59.png)

Any ideas on how to fix this on my end?

Thanks!

**Comment by shine-jayakumar** [comment]
I just ran the script and it works. Would you be able to share the log?

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: *******
[*] => Attempting to log in with ******
[*] => Validating login with xpath: //img[contains(@alt, " profile picture")]
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Finding Not Now button with xpath: //button[text()="Not now"]
[*] => Could not find Not Now button with xpath: //button[text()="Not now"]
[*] => Finding Not Now button with xpath: //div[@class="cmbtv"]/button
[*] => Could not find Not Now button with xpath: //div[@class="cmbtv"]/button
[*] => Finding Not Now button with xpath: //div[@class="_ac8f"]/button
[*] => Do not save login info: True
[*] => Opening target ******
[*] => [open_target]: Attempt - 1
[*] => [target: pinholepeek] No. of posts found: 122
[*] => [target: pinholepeek] Checking if pinholepeek is a private account
[*] => Failed to find text: This account is private
[*] => Failed to find text: This Account is private
[*] => Failed to find text: This Account is Private
[*] => [target: pinholepeek] Account not private
[*] => [target: pinholepeek] Opening first post
[*] => [target: pinholepeek] Number of posts to like: 1
[*] => [target: pinholepeek] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [target: pinholepeek] Comment disabled? No
[*] => [target: pinholepeek] Moving on to the next post
[*] => [target: pinholepeek] Waiting for 2 seconds
[*] => Script finished successfully
[*] => Total time taken: 100.5564 seconds

**Comment by shine-jayakumar** [comment]
> Hey no worries, here is the log as well as a screen capture of it.
> 
> 2022-10-29 19:10:13,315:**main**:146:INFO:Script started 2022-10-29 19:10:13,315:**main**:159:INFO:Downloading webdriver for your version of Chrome 2022-10-29 19:10:13,315:**main**:161:INFO:Initializing instagram user 2022-10-29 19:10:14,988:**main**:170:INFO:Setting target to: #mdcollective 2022-10-29 19:10:14,988:**main**:178:INFO:Attempting to log in with neato82.eth 2022-10-29 19:10:46,488:**main**:269:ERROR:Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active. Traceback (most recent call last): File "C:\Users\William Salas\Downloads_APPZ\insta-likecom-bot-master\instalikecombot.py", line 181, in raise Exception("Failed to login. Incorrect username/password, or 2 factor verification is active.") Exception: Failed to login. Incorrect username/password, or 2 factor verification is active. 2022-10-29 19:10:48,629:**main**:275:INFO:Total time taken: 35.3141 seconds
> 
>  221029_285_NVIDIA_Share.mp4

Thank you for sharing the video. I see that you're using version 1.4.

Current version is 2. Please clone the latest version and let me know how this goes

**Comment by shine-jayakumar** [comment]
Glad to hear that.
"It did hang at the save login info pop up for a bit and spit out some messages." - this is because it's trying to find that 'Not Now' button. Do let me know if there are any more bug/problems you find.
