### ISSUE TITLE
Read Comments and Repost ?

### ISSUE THREAD

**Issue by badplay** [shine-jayakumar/insta-likecom-bot#17]
Is it working to read a comment were i was linked or tagged and then repost to it with a comment from this post? the bot have to read the comments section and use the same what the other users writes and tag a friend of mine

structure

see i got a comment from user xy he writes inside a post

i think it is .... @myname

bot go to this post and wirte the same
i think it is .... @nameof a friend

**Comment by shine-jayakumar** [comment]
There is no feature as such. It chooses a random comment from a list of preloaded comments in the code. You can also specify a file with a list of comments.
