### ISSUE TITLE
Errow while running with hashtag

### ISSUE THREAD

**Issue by zgtibu** [shine-jayakumar/insta-likecom-bot#18]
[*] => Finding Not Now button with xpath: //button[text()="Not now"]
[*] => Do not save login info: True
[*] => Opening target #koramangala
[*] => [open_target]: Attempt - 1
[*] => [target: #koramangala] No. of posts found: 162638
[*] => [target: #koramangala] Checking if #koramangala is a private account
[*] => Failed to find text: This account is private
[*] => Failed to find text: This Account is private
[*] => Failed to find text: This Account is Private
[*] => [target: #koramangala] Account not private
[*] => [target: #koramangala] Opening first post
[*] => [target: #koramangala] Number of posts to like: 10
[*] => [target: #koramangala] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [like]: Attempt - 2

**Comment by shine-jayakumar** [comment]
We've noted a change in the interface when hashtags are opened. This is going to be implemented soon in the code.

**Comment by shine-jayakumar** [comment]
The bot is not working for hashtags
