### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jake22262** [shine-jayakumar/insta-likecom-bot#19]
What do I do now?
![image](https://user-images.githubusercontent.com/106946536/207234467-2229e8c0-f7f5-4d78-a59c-0a9c807f687c.png)

**Comment by Jake22262** [comment]
![image](https://user-images.githubusercontent.com/106946536/207234706-13609513-105d-4e12-bf13-5602924bee25.png)

**Comment by shine-jayakumar** [comment]
Are you using your own username and password? Please share the log and we can check what's going wrong.

**Comment by Jake22262** [comment]
Yes im using my own info just didnt wanna share it publicly. 
Microsoft Windows [Version 10.0.19044.2364]
---------------------------------------------------
C:\Users\Jake\Downloads\insta-likecom-bot-master\insta-likecom-bot-master>instalikecombot.py -u myuser -p mypass -t thebettergeneration

C:\Users\Jake\Downloads\insta-likecom-bot-master\insta-likecom-bot-master>
[main 2022-12-16T00:31:30.634Z] update#setState idle
[main 2022-12-16T00:31:31.535Z] UtilityProcess<1>: Creating new...
[main 2022-12-16T00:31:31.546Z] UtilityProcess<1>: received spawn event.
[main 2022-12-16T00:32:00.643Z] update#setState checking for updates
[main 2022-12-16T00:32:00.703Z] update#setState idle
[156:1215/163330.569:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by shine-jayakumar** [comment]
Try running the script like this:
`python3 instalikecombot.py -u shinej08 -p "Iw!lln0tt3lly0u@123" -t thebettergeneration`

If this doesn't work for you, you could also try creating a file named `.env` and put your credentials like so:
```
                                                              
INSTA_USER = 'yourusername'
INSTA_PASS = 'mypassword'
INSTA_TARGET = 'thebettergeneration'
```
Save this file, and run the script like this:
`python3 instalikecombot.py --loadenv`

I noticed that the logging isn't quite as it is supposed to be. It normally looks like this:
```
    
    insta-likecom-bot v.2.0
    Automates likes and comments on an instagram account or tag

    Author: Shine Jayakumar
    Github: https://github.com/shine-jayakumar
    
    
[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: thebettergeneration
[*] => Attempting to log in with myusername
[*] => Validating login with xpath: //img[contains(@alt, " profile picture")]
[*] => Login successful
[*] => Skipping Save Login Info
[*] => Finding Not Now button with xpath: //button[text()="Not now"]
```
