### ISSUE TITLE
Multiple account like and comenting?

### ISSUE THREAD

**Issue by mance819** [shine-jayakumar/insta-likecom-bot#22]
Is it possible to comment from different accounts on the same post?

**Comment by shine-jayakumar** [comment]
@mance819 You can run different instances of the script with different username/password. Each instance will open a different browser instance.

**Comment by mance819** [comment]
Also it would be great if it avoids pinned comments, lets say for example i want to like the latest post i would add '-np 1' but there is a pinned post. Wouldn't the pinned post always be the target? Great work though👍

**Comment by shine-jayakumar** [comment]
@mance819 that's right. Pinned posts should be skipped. I'll add this in next version. Thank you.
