### ISSUE TITLE
Post Date constraint for like/comment

### ISSUE THREAD

**Issue by datslo** [shine-jayakumar/insta-likecom-bot#24]
It would be great if the bot has the ability to limit likes/comments to posts of a certain age. Example: Only like 1 post per account if it was posted in the last 7 days. No one wants to like the last post from 2019 🤣

**Comment by shine-jayakumar** [comment]
@datslo "It would be great if the bot has the ability to limit likes/comments to posts of a certain age." - that's a good suggestion. It will be added in the next version.

**Comment by ap0l0** [comment]
> @datslo "It would be great if the bot has the ability to limit likes/comments to posts of a certain age." - that's a good suggestion. It will be added in the next version.

was this feature added? I think using this feature the other request I made for "recent posts" will also apply

**Comment by shine-jayakumar** [comment]
> > @datslo "It would be great if the bot has the ability to limit likes/comments to posts of a certain age." - that's a good suggestion. It will be added in the next version.
> 
> was this feature added? I think using this feature the other request I made for "recent posts" will also apply

This should be quite a useful feature. I will add this

**Comment by shine-jayakumar** [comment]
> > > @datslo "It would be great if the bot has the ability to limit likes/comments to posts of a certain age." - that's a good suggestion. It will be added in the next version.
> > 
> > 
> > was this feature added? I think using this feature the other request I made for "recent posts" will also apply
> 
> This should be quite a useful feature. I will add this

Recently added. Script can now filter posts based on recent n days. (use option -il or --inlast)
