### ISSUE TITLE
 change in the path to make comments

### ISSUE THREAD

**Issue by gustavoxrossi** [shine-jayakumar/insta-likecom-bot#25]
First I would like to praise your work, I spent the last few days researching and developing a solution similar to yours, but much less professional. I believe I have come across the same problem as you: 
the use of SELENIUM and changes in function paths.
I believe that in the current version, he is not able to locate the comments field.
"
[*] => [target: love] Commenting on the post
[*] => [comment]: Attempt - 1
[*] => [comment]: Attempt - 2
[*] => [comment]: Attempt - 3
[*] => [comment]: Attempt - 4
[*] => [target: love] Moving on to the next post
"

Is there any way to automate updating paths?

Again, congratulations on the job.

**Comment by shine-jayakumar** [comment]
@gustavoxrossi You can clone the recently updated version.
Thank you for your kind comments. We have updated the path for comment, however we're finding a way to find paths automatically.
