### ISSUE TITLE
Failed to login. Incorrect username/password

### ISSUE THREAD

**Issue by p0se** [shine-jayakumar/insta-likecom-bot#28]
When I run the script, I get the error: 
python3 instalikecombot.py --loadenv --delay 5 --numofposts 10 --headless --nocomments -br firefox
[<module>:294]:[ERROR]:Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.

I have disabled the 2 factor authentication.  
The access data are stored in the .env. 
I tested it with two IG accounts. 

If I use the command:
instalikecombot.py -u yourusername -p yourpassword -t thetarget
[1] 15967
-bash: yourpassword: command not found
root@insta:/home/insta-likecom-bot# Error: username, password, and target are required.

**Comment by shine-jayakumar** [comment]
> When I run the script, I get the error: python3 instalikecombot.py --loadenv --delay 5 --numofposts 10 --headless --nocomments -br firefox [:294]:[ERROR]:Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.
> 
> I have disabled the 2 factor authentication. The access data are stored in the .env. I tested it with two IG accounts.
> 
> If I use the command: instalikecombot.py -u yourusername -p yourpassword -t thetarget [1] 15967 -bash: yourpassword: command not found root@insta:/home/insta-likecom-bot# Error: username, password, and target are required.

enclose the password in single quotes when running it from terminal:
`python3 instalikecombot.py -u youusername -p 'youRpaS5w0rd' -t haiku -nc`
