### ISSUE TITLE
Match at least 2 or 3 hashtags from a list

### ISSUE THREAD

**Issue by Skuwwy** [shine-jayakumar/insta-likecom-bot#29]
Hi there, is it possible to make this tool interact  (like/comment) with posts that match a minimum of 2 or 3 tags from a pre-defined list? This is to narrow down the content that would be more relevant to me.

**Comment by shine-jayakumar** [comment]
Added feature :
 * Filter posts based on tags
 * Option to match all tags from a list, or a specific number of tags

**Comment by Skuwwy** [comment]
Thank you!
