### ISSUE TITLE
Attempting to Login

### ISSUE THREAD

**Issue by victorbraga8** [shine-jayakumar/insta-likecom-bot#3]
Why i receive the error "Failed to login. Incorrect username/password, or 2 factor verification is active.", even i can login sucessfully ?

The error is shown after my feed appear in the screen.

Bellow there's my error message and script.

Script: py instalikecombot.py myusername mypassword "#netgeo" -np 20

Error: Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.
[*] => Total time taken: 37.839 seconds

**Comment by shine-jayakumar** [comment]
The bot was tested after the issue had been reported. It works fine mostly unless Instagram sometimes prevents login attempts from unknown locations or automated instance of browser (chromedriver/geckodriver).

Instagram had made changes to the classnames with which instalikecombot finds the components like, buttons, links, textboxes etc. Although this couldn't be the issue, we're looking forward to fix the issue as soon as possible.

**Comment by shine-jayakumar** [comment]
Tested the functionality at few different instances. No problems reported. Instagram does sent user notifications about login detected from other locations. This could be one of the reason for instagram not allowing to login. If the script fails to login, it logs it as incorrect username/password even when your password could be correct. This can be treated as a separate issue, while we're still looking out for reason Instagram might block automated login attempts and alternate ways to provide uninterrupted experience.
