### ISSUE TITLE
Login failure with Chrom/Firefox/headless

### ISSUE THREAD

**Issue by Lenerd88** [shine-jayakumar/insta-likecom-bot#30]
Hey everyone,

I got issues while login.

[2023-03-28 09:19:15,800]:[__main__]:[<module>:144]:[INFO]:Script started
[2023-03-28 09:19:15,800]:[__main__]:[<module>:157]:[INFO]:Downloading webdriver for your version of Chrome
[2023-03-28 09:19:15,801]:[__main__]:[<module>:159]:[INFO]:Initializing instagram user
[2023-03-28 09:19:18,123]:[__main__]:[<module>:168]:[INFO]:Setting target to: 'target'
[2023-03-28 09:19:18,123]:[__main__]:[<module>:182]:[INFO]:Attempting to log in with 'username'
[2023-03-28 09:19:20,097]:[__main__]:[<module>:294]:[ERROR]:Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active.
[2023-03-28 09:19:22,168]:[__main__]:[<module>:300]:[INFO]:Total time taken: 6.3697 seconds

-----------------------------

Command I used:
python instalikecombot.py --loadenv --delay 5 --numofposts 10 --nocomments

Also tried it with -u user -p password, headless, forcing firefox etc.

My Credentials are working, I logged in manual with both browsers, no 2FA.
Are you still working on this project and could help me?

Thanks!

**Comment by shine-jayakumar** [comment]
> Hey everyone,
> 
> I got issues while login.
> 
> [2023-03-28 09:19:15,800]:[**main**]:[:144]:[INFO]:Script started [2023-03-28 09:19:15,800]:[**main**]:[:157]:[INFO]:Downloading webdriver for your version of Chrome [2023-03-28 09:19:15,801]:[**main**]:[:159]:[INFO]:Initializing instagram user [2023-03-28 09:19:18,123]:[**main**]:[:168]:[INFO]:Setting target to: 'target' [2023-03-28 09:19:18,123]:[**main**]:[:182]:[INFO]:Attempting to log in with 'username' [2023-03-28 09:19:20,097]:[**main**]:[:294]:[ERROR]:Script ended with error : Failed to login. Incorrect username/password, or 2 factor verification is active. [2023-03-28 09:19:22,168]:[**main**]:[:300]:[INFO]:Total time taken: 6.3697 seconds
> 
> Command I used: python instalikecombot.py --loadenv --delay 5 --numofposts 10 --nocomments
> 
> Also tried it with -u user -p password, headless, forcing firefox etc.
> 
> My Credentials are working, I logged in manual with both browsers, no 2FA. Are you still working on this project and could help me?
> 
> Thanks!
```
Ran it to check. It works fine on Chrome. There are some known issues in Firefox which are to be fixed, but I see that it works fine in Chrome.

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Initializing instagram user
[*] => Setting target to: #target
[*] => Attempting to log in with myusername
[*] => Validating login with xpath: //img[contains(@alt, " profile picture")]
[*] => Login successful
[*] => Opening target #target
[*] => [open_target]: Attempt - 1
[*] => [target: #target] No. of posts found: 102
[*] => [target: #target] Checking if #target is a private account
[*] => Failed to find text: This account is private
[*] => Failed to find text: This Account is private
[*] => Failed to find text: This Account is Private
[*] => [target: #target] Account not private
[*] => [target: #target] Opening first post
[*] => [target: #target] Number of posts to like: 10
[*] => [target: #target] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 2
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 3
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 4
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 5
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 6
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 7
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => [target: #target] Liking post: 8
[*] => [like]: Attempt - 1
[*] => [target: #target] Comment disabled? No
[*] => [target: #target] Moving on to the next post
[*] => [target: #target] Waiting for 5 seconds
[*] => Total time taken: 71.7119 seconds
```
