### ISSUE TITLE
[Feature Request] Like Post Comments

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#35]
Is there a way to like/view stories and also like first top 1-5 comments from posts on a tag?

**Comment by shine-jayakumar** [comment]
That's a really good feature suggestion. This will surely be added to the script soon.

**Comment by ap0l0** [comment]
> That's a really good feature suggestion. This will surely be added to the script soon.

Great! 

Also is there a way to filter to "recent" posts/stories, way easier to get crazy engagement from posts/stories that are recent (last  4 hours)


Is there a link for donations for the project?

**Comment by shine-jayakumar** [comment]
> > That's a really good feature suggestion. This will surely be added to the script soon.
> 
> Great!
> 
> Also is there a way to filter to "recent" posts/stories, way easier to get crazy engagement from posts/stories that are recent (last 4 hours)
> 
> Is there a link for donations for the project?

Again, that's a great addition and make the script more useful. I will add a donation link. Thank you @ap0l0

**Comment by ap0l0** [comment]
Nice push! Will checkit out later

The donation button is not working, it seems like is limited to donations only from your country. Do you have paypal?

<img width="584" alt="image" src="https://user-images.githubusercontent.com/14894967/230772989-4bdae591-223a-4920-85ed-b5d4228937ea.png">

**Comment by ap0l0** [comment]
you are a beast, it's working great

<img width="933" alt="image" src="https://user-images.githubusercontent.com/14894967/230773310-a2d9f67d-a54d-4715-bc70-9d033dd593a7.png">

**Comment by shine-jayakumar** [comment]
> you are a beast, it's working great
> 
> <img alt="image" width="933" src="https://user-images.githubusercontent.com/14894967/230773310-a2d9f67d-a54d-4715-bc70-9d033dd593a7.png">

Great! Thanks for your kind words. Glad it's working for you.

**Comment by shine-jayakumar** [comment]
> Nice push! Will checkit out later
> 
> The donation button is not working, it seems like is limited to donations only from your country. Do you have paypal?
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/14894967/230772989-4bdae591-223a-4920-85ed-b5d4228937ea.png">

I do not have paypal unfortunately, but I have disconnected Stripe so it should work it now. Thanks a lot again.
