### ISSUE TITLE
[Improvement] Save Session for Two-Factor Authentication

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#36]
The script doesn't save the session or clicks on "Save Info" when two factor is enable so everytime there is a change on the script the SMS has to be validated:

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/14894967/230748188-08efdf09-cd24-4326-959b-59d3964ad7b0.png">

After login it the first time I would select the "Save Info" but it doesn't work because it seems like the session is reset everytime the script runs.

**Comment by shine-jayakumar** [comment]
> The script doesn't save the session or clicks on "Save Info" when two factor is enable so everytime there is a change on the script the SMS has to be validated:
> 
> <img alt="image" width="1257" src="https://user-images.githubusercontent.com/14894967/230748188-08efdf09-cd24-4326-959b-59d3964ad7b0.png">
> 
> After login it the first time I would select the "Save Info" but it doesn't work because it seems like the session is reset everytime the script runs.

Script uses a webdriver which launches an instance of Chrome designed for automation. Clicking on "Save Info" button wouldn't save the sessions in these instance. Loading a profile while starting the script could be a useful addition. I will add this too.

**Comment by ap0l0** [comment]
Hi @shine-jayakumar , looks like the not using the same session causes IG to recognize the script as a new device every single time is used and blocks actions because of this. Is there a way to make the session persist so it looks like a regular device/session instead of a new session everytime?

**Comment by ap0l0** [comment]
As suspected IG servers are blocking now login attempts:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/14894967/234215295-64c88bea-b92d-443b-9cb3-aa4171cf8ac5.png">

Please note that this will happen even with two-factor disable, it's just IG doesn;t like repeated logins

**Comment by shine-jayakumar** [comment]
> As suspected IG servers are blocking now login attempts:
> 
> <img alt="image" width="885" src="https://user-images.githubusercontent.com/14894967/234215295-64c88bea-b92d-443b-9cb3-aa4171cf8ac5.png">
> 
> Error 401: Server Unahotirized
> 
> Please note that this will happen even with two-factor disable, it's just IG doesn;t like repeated logins

The next push will have option to load a chrome profile. This would allow users to save the login and wouldn't require multiple logins.

**Comment by shine-jayakumar** [comment]
Closing this issue since this has been implemented in v.3.0
