### ISSUE TITLE
[Feature Request] Like/React to Stories

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#39]
- Able to like/react to stories for a tag, location or followers of an account

**Comment by shine-jayakumar** [comment]
> * Able to like/react to stories for a tag, location or followers of an account

This should be added soon.

**Comment by shine-jayakumar** [comment]
options added:

- -ls, --likestory - to like a story
- -cs, --commentstory - to comment on a story
- -rr, --reloadrepeat - to reload target a specific number of times

please clone the latest push (v.2.7)

**Comment by ap0l0** [comment]
What's the reloadrepeat? 

also, you don't have one for "view story"?

**Comment by ap0l0** [comment]
I am using this command but no stories are open:

`-t "#miami" -nc -np 700 -mr -ls`

**Comment by ap0l0** [comment]
I think it doesn't work with posts from tags? 

```
[*] => [target: #miami] No. of posts found: 85344988
[*] => [target: #miami] Checking if #miami is a private account
[*] => Failed to find text: This account is private
[*] => Failed to find text: This Account is private
[*] => Failed to find text: This Account is Private
[*] => [target: #miami] Account not private
[*] => [target: #miami (Most Recent)] Opening first post
[*] => [target: #miami] Number of posts to like: 700
[*] => [target: #miami] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [target: #miami] Comment disabled? No
[*] => [target: #miami] Moving on to the next post
```

**Comment by shine-jayakumar** [comment]
> "view story"?

We don't have an option to just view the stories. It can be added though

**Comment by shine-jayakumar** [comment]
> What's the reloadrepeat?
> 
> also, you don't have one for "view story"?

reloadrepeat - reloads the page for a target x times. This can be used with --mostrecent. Once the script is done like certain number of posts, the -rr (--reloadrepeat) would refresh the page and start interacting with the newly added posts.

**Comment by ap0l0** [comment]
> reloadrepeat - reloads the page for a target x time

X Times is in seconds or amount of posts?

**Comment by shine-jayakumar** [comment]
> > reloadrepeat - reloads the page for a target x time
> 
> X Times is in seconds or amount of posts?
> 
> I see in the documentation that -rr 5 but not sure if its 5 minutes or 5 posts?

--rr 5, would refresh the page 5 times.
So, when used like:` --mostrecent -np 10 -rr 5` script would like 10 recent posts from most recent section and then refresh the page after waiting for a couple of seconds. This would allow enough time for more recent posts to be added and script would get fresh posts every time to interact with. The page refresh happens 5 times (-rr 5).

**Comment by shine-jayakumar** [comment]
Closing this issue as it's available since v.2.7
