### ISSUE TITLE
[Question] List by Recent instead of Top tags

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#40]
Testing the script it looks like it always loads the "top" filter for tags. Is there a way to filter by "recent" instead since engagement is way higher there since posts are more fresh.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/14894967/230815296-f27c31c9-e964-4412-abb3-b43c493ca730.png">

**Comment by shine-jayakumar** [comment]
I think this should be fixed with the recently added `-il, --inlast` argument that targets posts within last n days. In the next push, I will add a hours, minutes filter to increase the depth of the search.
