### ISSUE TITLE
posible to multiple account?

### ISSUE THREAD

**Issue by anjingadalahasu** [shine-jayakumar/insta-likecom-bot#43]
how to run multiple account in file .env

thanks

**Comment by ap0l0** [comment]
> how to run multiple account in file .env
> 
> thanks

I think the best way is to run multiple times the script in parallel. You can have probably a folder for each IG account

**Comment by shine-jayakumar** [comment]
> how to run multiple account in file .env
> 
> thanks

@anjingadalahasu Currently, the script only accept one target from .env. However, you could run the script parallelly as suggested by @ap0l0 . Accepting multiple users from .env/command line should be added in the next version.

**Comment by shine-jayakumar** [comment]
Closing this issue as this feature is available since v.3.0
