### ISSUE TITLE
[Feature Request] Most Recent Filter for Explore/Tags Page (crazy hack)

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#45]
Hi, doing tests with your script and manual tests I realized a hidden hack to get massive followers. Your previous build allows to filter post not older than X days but there is a better way to this done and also has like 400% increase in followers because the users are online at the moment of the action.

The steps to get this done are as follow:

New parameter (-rp "Engage with recent posts only")

1. Script visits `https://www.instagram.com/explore/tags/travel/` (#travel will be the tag in this case)
2. It ignores the "Top Posts" and scrolls down to where it says "Most Recent"
3. It stars engaging with those recent posts. The big difference and the magic is that if you check all the posts have "created seconds ago". I manually did like a few of them and the results were incredible because most of those users just posted the content and follow back since they are online while we do the engagement.
4. After 10-20 posts processed refresh the page and start from the "Most Recent" again. **This step is very important**, because it will be engaging always with the latest posts which are created "seconds/minutes ago"

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/14894967/231549279-7e17f28d-9069-4077-9d81-71e6e0024378.png">

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/14894967/231549208-07285472-f71f-4ad5-b6f4-d5f946ff5188.png">

**Comment by shine-jayakumar** [comment]
This has been implemented already in the lastest version **v.2.6**

- old option -rp (recent posts - which only checks if the post is within last n days) has been removed
- new option is -mr (most recent) - which does exactly what you're suggesting. It scrolls down to most recent posts
- new option -il (in last) has been added. It allows filtering of posts in last nYears, nMonths, nDays, nHours, nMins, nSecs

**Comment by ap0l0** [comment]
It's working great!

**Comment by shine-jayakumar** [comment]
> It's working great!

I am glad it works for you. :)

**Comment by ap0l0** [comment]
Literally used it for my city as a tag and got about 10 follow requests in 20 min

**Comment by Skuwwy** [comment]
> This has been implemented already in the lastest version **v.2.6**
> 
> * old option -rp (recent posts - which only checks if the post is within last n days) has been removed
> * new option is -mr (most recent) - which does exactly what you're suggesting. It scrolls down to most recent posts
> * new option -il (in last) has been added. It allows filtering of posts in last nYears, nMonths, nDays, nHours, nMins, nSecs
> 
> Step 4, sounds really interesting. It will be implemented in the next push along with some other additional features.

Question, does the bot automatically skip already liked/commented post or does it do it again? I am posting it on this thread because I am really interested in trying out this most recent feature.
