### ISSUE TITLE
[BUG] Option to like stories shows error

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#48]
```
[*] => [pause_story] Error: TimeoutException
[*] => [get_total_stories] Error: TimeoutException
```

Am I putting the command wrong? I can't find a way to make this feature work, I am checking the browser and some users have stories but it doesn't open the stories.

This is the command I am using:

`python3 instalikecombot.py -u myuser -p mypass -t "komodoloungemiami" -ff -ls -nc -fa 600 -np 1
`

EDIT:
It likes some stories, but not sure why others it wont detect it. Can you add in the console when it views and also when it likes a story successfully?

**Comment by shine-jayakumar** [comment]
Methods in the script returned a false positive even when there wasn't a story present or the account was private.
Changes in the latest version:
- added -os, --onlystory -> allows you to target only story
- private account checks before attempting to open the story

**Comment by ap0l0** [comment]
@shine-jayakumar haven't been able to test this but seems like the perfect solution for it. I would also add a parameter in the "-ls" to decide how many stories to like "-ls 2" because on my tests some people have like 30 stories and the script likes all of them

**Comment by shine-jayakumar** [comment]
> @shine-jayakumar haven't been able to test this but seems like the perfect solution for it. I would also add a parameter in the "-ls" to decide how many stories to like "-ls 2" because on my tests some people have like 30 stories and the script likes all of them

This should be added, along with some additional checks for user activity.

**Comment by shine-jayakumar** [comment]
Closing this issue as this has been implemented in v.3.0 and above.
