### ISSUE TITLE
[Account Control] Count and Limit the amount of events from the script

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#50]
I am currently talking with Facebook Creator Team (my account is legacy verified) and I am discussing the reason my account was restricted from "liking posts". The reason is obvious, this script was overused by me, so I am wondering if we can add a way to control this — here are some suggestions:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/14894967/232098355-16de0fc4-e8b5-414a-a8ee-0f0d0ec36401.png">

1. Make the script count all actions, so far IG seems to treat the restrictions differently based on the action for example:

- View Profile (~800-1000 a day for my account, other might differ)
- Like Post (~400-600)
- Like Comments (~600-800)
- View Story (no idea)
- Like Story (no idea)

2. Stop the script as soon as the Block alert is shown by Instagram:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/14894967/232099214-7fa4b106-6f61-4c32-97ad-4a0f9021bdd9.png">

@shine-jayakumar just adding another screenshot of a different softban message, this appears after opening too many profiles (specially using -ff):

<img width="819" alt="image" src="https://user-images.githubusercontent.com/14894967/235031813-86856b46-437f-44b5-a5a2-17173508b032.png">

`<div class="_a9-v"><div class="_a9-y"><span class="x1lliihq x1plvlek xryxfnj x1n2onr6 x193iq5w xeuugli x1fj9vlw x13faqbe x1vvkbs x1s928wv xhkezso x1gmr53x x1cpjm7i x1fgarty x1943h6x x1i0vuye x1ms8i2q xo1l8bm x5n08af x4zkp8e xw06pyt x10wh9bi x1wdrske x8viiok x18hxmgj" style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height:25px;">Try Again Later</span><span class="x1lliihq x1plvlek xryxfnj x1n2onr6 x193iq5w xeuugli x1fj9vlw x13faqbe x1vvkbs x1s928wv xhkezso x1gmr53x x1cpjm7i x1fgarty x1943h6x x1i0vuye xvs91rp xo1l8bm x1roi4f4 x1tu3fi x3x7a5m x10wh9bi x1wdrske x8viiok x18hxmgj" style="line-height: var(--base-line-clamp-line-height); --base-line-clamp-line-height:18px;">We restrict certain activity to protect our community.</span></div><div class="_a9-z"><button class="_a9-- _a9_0" tabindex="0">Report a problem</button><button class="_a9-- _a9_1" tabindex="0">OK</button></div></div>`

3. Rework the --delay option , for example by default it selects a random number of seconds but if you add `-d 15` then it waits exact 15 seconds to perform next action. The most "human-like" solution I believe should be to change delay like this:
 
`-d 15` = Wait 15 seconds (like it is now)
 `-d 0-15` = Wait randomly seconds between 0 and 15
`-d 10-40` = Wait randomly between 10 to 40 seconds

This way the script will act less exact and more human-like

4. Make the script share the total actions performed as it works, like a "status" so we can see if we are going over the limit and stop it.

**Comment by shine-jayakumar** [comment]
@ap0l0 Sad it happened but I guess the restriction will be lifted soon. 
- **point # 3**: currently, if delay is not specified, it selects a random number (0-10 seconds). Accepting a range would be a nice addition
- **point # 4**: in the lastest version, I've added the status to the end of the script (number of likes, posts viewed, stories likes etc.). I can make it show the status while it's running.
- **point #1**: script is currently counting the actions but since we don't know the exact limit for each action for an account, we're going to have to assume a number. I'll have to check the IG guidelines if there's anything specified there.
- **point # 2**: should a nice addition.

**Comment by ap0l0** [comment]
> * **point # 1**: script is currently counting the actions but since we don't know the exact limit for each action for an account, we're going to have to assume a number. I'll have to check the IG guidelines if there's anything specified there.

This number changes and is dynamic for each account based on age, activity, etc. We will have to leave each user to control the actions per day according to their account.
