### ISSUE TITLE
Multiple Targets via list or array?

### ISSUE THREAD

**Issue by Cryptoom** [shine-jayakumar/insta-likecom-bot#53]
A wonderful Script and thanks for your work.
is there a way to add multiple Targets like a list of hashtags or profiles?

**Comment by shine-jayakumar** [comment]
> A wonderful Script and thanks for your work. is there a way to add multiple Targets like a list of hashtags or profiles?

Thank you @Cryptoom Multiple target should be added in the next version.

**Comment by ap0l0** [comment]
> > A wonderful Script and thanks for your work. is there a way to add multiple Targets like a list of hashtags or profiles?
> 
> Thank you @Cryptoom Multiple target should be added in the next version.

Hey Shine, no words to the 3.0 version. I haven't been able to test it yet but you are a beast, wonderful push. 

Question about the targets, in the docs it seems like you can add not only tags but also user profiles?

How will the script manage that? Finish by order? For example:

Targets:
#sometaghere
usernamejohn
#anothertag

The script will perform actions by the order of those targets?

**Comment by shine-jayakumar** [comment]
> > > A wonderful Script and thanks for your work. is there a way to add multiple Targets like a list of hashtags or profiles?
> > 
> > 
> > Thank you @Cryptoom Multiple target should be added in the next version.
> 
> Hey Shine, no words to the 3.0 version. I haven't been able to test it yet but you are a beast, wonderful push.
> 
> Question about the targets, in the docs it seems like you can add not only tags but also user profiles?
> 
> How will the script manage that? Finish by order? For example:
> 
> Targets: #sometaghere usernamejohn #anothertag
> 
> The script will perform actions by the order of those targets?

That's right. Script will interact with the account/tag which it finds first in the list. For example, if you want 'usernamejohn' to be processed first, put that in the top of the list.
Please clone the latest version as there had been some bug fixes. Thank you for your kind words, @Cryptoom. Appreciate it :)
