### ISSUE TITLE
[Feature Request] Target "Related" Accounts

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#56]
The user provide the target of an account example: -t cristiano and the bot will interact with related accounts. This method is more safe than the "-ff" which causes almost certantly a softban after 110 requests.

The related accounts can be seen once you open a profile and click on: 
<img width="47" alt="image" src="https://user-images.githubusercontent.com/14894967/235031179-c008b84a-4ff0-4b25-b16e-1654f9a4e077.png">

The main benefit of "related accounts" is that it shows relatable accounts to the audience you are looking for without risking a softban since is a natural navigation.

The command could be something like:

```
-ra (Target related accounts)
python3 instalikecombot.py -u user -p pass -t "cristianoronald" -ra 
```

**Comment by shine-jayakumar** [comment]
That's another great feature addition. I had never used that one before. I noticed that it had only fewer accounts to scroll through and would surely be related to the target account as it's hand picked by Instagram's algorithm. It should be added soon.

**Comment by ap0l0** [comment]
> That's another great feature addition. I had never used that one before. I noticed that it had only fewer accounts to scroll through and would surely be related to the target account as it's hand picked by Instagram's algorithm. It should be added soon.

I would hold on this feature. I did some manual tests and there is a way to make this very powerful in combination with something else. I will create another ticket for it to document it better.
