### ISSUE TITLE
[Feature Request] Send story reactions

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#61]
Seems like the script can send reactions too, not only "like". See screenshot below captured when the script was running:

![image](https://user-images.githubusercontent.com/14894967/235545940-2a038351-5b1f-4002-8265-810a1f20152d.png)

**Comment by shine-jayakumar** [comment]
Absolutely! Script can send comments/emojis as reactions. Just use the 'commentstory' argument.

**Comment by ap0l0** [comment]
> Absolutely! Script can send comments/emojis as reactions. Just use the 'commentstory' argument.

This command is no longer working:

 -ff -ls -nc -fa 100

Before it used to get 100 followers of the target and start engaging. Now it gets 100 folloers, goes to the first one and tries to get another 100, and like that non-stop.

**Comment by shine-jayakumar** [comment]
> > Absolutely! Script can send comments/emojis as reactions. Just use the 'commentstory' argument.
> 
> This command is no longer working:
> 
> -ff -ls -nc -fa 100
> 
> Before it used to get 100 followers of the target and start engaging. Now it gets 100 folloers, goes to the first one and tries to get another 100, and like that non-stop.

This has been fixed now in 3.0.2. Do let me know if it's working for you, and if you find any other issues.
