### ISSUE TITLE
[Account Control] Limits of engagement and avoiding soft-bans

### ISSUE THREAD

**Issue by ap0l0** [shine-jayakumar/insta-likecom-bot#65]
Hi @shine-jayakumar — I have used your tool for weeks now, amazing results and latest updates just make it even better. The biggest problem is controlling the soft-bans that IG puts for 24h-48h when overusing it. 

I took time to research and test it personally and here is some information that could be useful:

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
IG API Limits:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

***** Avoid using Instagram on multiple devices simultaneously *****

Post Likes: 1,000 likes /day
Maximum Likes: 350 likes /hour
Story views: 1,000-1500 /day
Like/react to stories: 600-800 /day
Like comments: No official limit, keep number below 2,000
Profile Views: 800 /day
Maximum Profile Views: 140 /hour

Now, under those numbers I have avoided softbans so far. There are a few tricks, like not using more than one device at the time that are very important. The other most popular softban is based on profile views, not really on Likes, if the script visits too many profiles +140-150 per hour it could cause a softban.

I suggest adding a new module for account control, with this limits on the configuration/profile file. Ideally, save locally the engagement/actions made so if the script runs multiple times the actions are recorded and keep the account safe.

**Comment by shine-jayakumar** [comment]
Added in v.3.0.4
