### ISSUE TITLE
Feature require - skip commenting on posts which have been commented.

### ISSUE THREAD

**Issue by imakou** [shine-jayakumar/insta-likecom-bot#72]
AS title, wish to have a feature to skip commenting on posts which have been commented already.

I noticed that we would put multiple comments on the same posts if the posts meet the tags we setup.

Thanks ~

**Comment by imakou** [comment]
@shine-jayakumar 👍 
Hopefully, we can have this feature in the next release? 😄 

Thanks

**Comment by m-deane** [comment]
Bumping this - is there anyway to skip multiple comments on posts?

Thanks :)

**Comment by shine-jayakumar** [comment]
Closing this issue as this is added in v.3.0.4
