### ISSUE TITLE
Cannot login - Chromedriver not found

### ISSUE THREAD

**Issue by digitizesuccess** [shine-jayakumar/insta-likecom-bot#79]
Just like the title says. It's been working for a few days with no issues. I used it 12 hours ago and it worked fine. Now I am getting a Chromedriver not found error after attempting the following script:  `/usr/local/bin/python3 /Users/xxx/insta-likecom-bot/ilcbot.py -u xxx -p xxx  -t xxx -np 3 -nc -ff -mr --delay 2,20 `

The error is as follows:

`[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Loading Instagram
[*] => Script ended with error
[*] => Error: [ValueError] - There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_mac64.zip
Traceback (most recent call last):
  File "/Users/xxx/insta-likecom-bot/ilcbot.py", line 49, in <module>
    insta = Insta(
            ^^^^^^
  File "/Users/xxxx/insta-likecom-bot/modules/instafunc.py", line 132, in __init__
    executable_path=ChromeDriverManager(path=os.path.join(self.driver_baseloc, 'chrome')).install(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_mac64.zip
[*] => Total time taken: 0.8177 seconds`

**Comment by jakkul** [comment]
same issue here

**Comment by jakkul** [comment]
might be related to this https://stackoverflow.com/questions/76724939/there-is-no-such-driver-by-url-https-chromedriver-storage-googleapis-com-lates

**Comment by digitizesuccess** [comment]
agreed. I updated my Chromedriver via pip and now the error changed

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Loading Instagram
[*] => Script ended with error
[*] => Error: [TypeError] - ChromeDriverManager.__init__() got an unexpected keyword argument 'path'
Traceback (most recent call last):
  File "/Users/xxx/insta-likecom-bot/ilcbot.py", line 49, in <module>
    insta = Insta(
            ^^^^^^
  File "/Users/xxx/insta-likecom-bot/modules/instafunc.py", line 132, in __init__
    executable_path=ChromeDriverManager(path=os.path.join(self.driver_baseloc, 'chrome')).install(),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'path'
[*] => Total time taken: 0.0064 seconds

**Comment by shine-jayakumar** [comment]
@digitizesuccess @jakkul The latest version for Chrome webdriver available is ChromeDriver 114.0.5735.90, i.e., chrome web driver for v.115 isn't listed on [https://chromedriver.chromium.org/downloads](https://chromedriver.chromium.org/downloads).

However, you could download it from [https://googlechromelabs.github.io/chrome-for-testing/#stable](https://googlechromelabs.github.io/chrome-for-testing/#stable) for your operating system, and follow these steps:

1. Extract the compressed file and place the `chromedriver` in the same location as the script
2. Edit line # 131 of `modules/instafunc.py` and change it to 
   `self.driver = webdriver.Chrome(executable_path='/path/of/the/chromedriver/',  options=options)`

This should be able to let the script use the chromedriver you just downloaded.

**Comment by digitizesuccess** [comment]
It doesn't seem to be working. New error though so it getting somewhere. 

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Loading Instagram
[*] => Script ended with error
[*] => Error: [WebDriverException] - Message: unknown error: cannot find Chrome binary
Stacktrace:
0   chromedriver                        0x0000000100b72a58 chromedriver + 4991576
1   chromedriver                        0x0000000100b69fa3 chromedriver + 4956067
2   chromedriver                        0x000000010071c607 chromedriver + 443911
3   chromedriver                        0x000000010074a4b7 chromedriver + 631991
4   chromedriver                        0x000000010074964c chromedriver + 628300
5   chromedriver                        0x000000010079224c chromedriver + 926284
6   chromedriver                        0x00000001007915af chromedriver + 923055
7   chromedriver                        0x0000000100788633 chromedriver + 886323
8   chromedriver                        0x00000001007546f9 chromedriver + 673529
9   chromedriver                        0x00000001007558de chromedriver + 678110
10  chromedriver                        0x0000000100b2e8a9 chromedriver + 4712617
11  chromedriver                        0x0000000100b338b4 chromedriver + 4733108
12  chromedriver                        0x0000000100b3a799 chromedriver + 4761497
13  chromedriver                        0x0000000100b3460a chromedriver + 4736522
14  chromedriver                        0x0000000100b0787c chromedriver + 4552828
15  chromedriver                        0x0000000100b52c08 chromedriver + 4860936
16  chromedriver                        0x0000000100b52d87 chromedriver + 4861319
17  chromedriver                        0x0000000100b62edf chromedriver + 4927199
18  libsystem_pthread.dylib             0x00007ff807f7c1d3 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff807f77bd3 thread_start + 15
Traceback (most recent call last):
  File "/Users/xxx/insta-likecom-bot/ilcbot.py", line 49, in <module>
    insta = Insta(
            ^^^^^^
  File "/Users/xxx/insta-likecom-bot/modules/instafunc.py", line 131, in __init__
    self.driver = webdriver.Chrome(executable_path='/Users/xxx/insta-likecom-bot/chromedriver-mac-x64/chromedriver',  options=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
0   chromedriver                        0x0000000100b72a58 chromedriver + 4991576
1   chromedriver                        0x0000000100b69fa3 chromedriver + 4956067
2   chromedriver                        0x000000010071c607 chromedriver + 443911
3   chromedriver                        0x000000010074a4b7 chromedriver + 631991
4   chromedriver                        0x000000010074964c chromedriver + 628300
5   chromedriver                        0x000000010079224c chromedriver + 926284
6   chromedriver                        0x00000001007915af chromedriver + 923055
7   chromedriver                        0x0000000100788633 chromedriver + 886323
8   chromedriver                        0x00000001007546f9 chromedriver + 673529
9   chromedriver                        0x00000001007558de chromedriver + 678110
10  chromedriver                        0x0000000100b2e8a9 chromedriver + 4712617
11  chromedriver                        0x0000000100b338b4 chromedriver + 4733108
12  chromedriver                        0x0000000100b3a799 chromedriver + 4761497
13  chromedriver                        0x0000000100b3460a chromedriver + 4736522
14  chromedriver                        0x0000000100b0787c chromedriver + 4552828
15  chromedriver                        0x0000000100b52c08 chromedriver + 4860936
16  chromedriver                        0x0000000100b52d87 chromedriver + 4861319
17  chromedriver                        0x0000000100b62edf chromedriver + 4927199
18  libsystem_pthread.dylib             0x00007ff807f7c1d3 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff807f77bd3 thread_start + 15

[*] => Total time taken: 0.5417 seconds

**Comment by digitizesuccess** [comment]
Thanks! its fixed. Make sure you download the version of Chrome for automated testing and put it in the same folder.
