### ISSUE TITLE
Issue on downloading chromnium 

### ISSUE THREAD

**Issue by imakou** [shine-jayakumar/insta-likecom-bot#80]
As title, the log is attached.
Thanks for taking a look!

![image](https://github.com/shine-jayakumar/insta-likecom-bot/assets/1507950/7a82dbee-e319-4d3a-b8a9-9996ef8dbdf5)

**Comment by gelbxx** [comment]
I have the same issue

![image](https://github.com/shine-jayakumar/insta-likecom-bot/assets/141627695/6a8784f8-4eb2-4bcd-a008-f1a29fd4cbe0)

**Comment by gelbxx** [comment]
Does anybody please have any idea, how to solve this? Thank you!

**Comment by shine-jayakumar** [comment]
@imakou @gelbxx  please clone the latest version. Selenium driver issue has been fixed.

**Comment by rmwvamp** [comment]
the above error is resolved but it still shows an error
![image](https://github.com/shine-jayakumar/insta-likecom-bot/assets/34397433/13b551ff-a496-4282-9275-5cd9184263c4)

**Comment by shine-jayakumar** [comment]
@gelbxx Make sure you have selenium==4.11.2 and webdriver-manager==4.0.0 installed. Even though you pull the latest version, it would still have the old versions of selenium and webdriver-manager installed in your python environment. Let me know if this is the case.
