### ISSUE TITLE
Having trouble leaving comments

### ISSUE THREAD

**Issue by michael-duda** [shine-jayakumar/insta-likecom-bot#83]
First off, love your code. Easily the best of its kind on here!

I am having trouble with the program not posting comments. For the 50 posts I queued up, 3 of those received comments. Any ideas? Is there a way to specify that each post should receive a comment, and if not, to skip over it? Thank you.

**Comment by michael-duda** [comment]
> @michael-duda Glad that you find it useful. The script is supposed to place comments on every post. Please share the parameters you used (excluding the username/password/target) and the logs. I can take a look at it.

Thank you for the response.

This is the json profile I have:

{
    "username": "XXX",
    "password": "XXX",
    "target": randomaccount,
    "numofposts": "100",
    "findfollowers": true,
    "followersammount": 100,
    "comments": "comments.txt",
    "delay": "5,9"
}

**Comment by michael-duda** [comment]
also, is it supposed to process ALL a targets followers before running?

**Comment by shine-jayakumar** [comment]
> > @michael-duda Glad that you find it useful. The script is supposed to place comments on every post. Please share the parameters you used (excluding the username/password/target) and the logs. I can take a look at it.
> 
> Thank you for the response.
> 
> This is the json profile I have:
> 
> { "username": "XXX", "password": "XXX", "target": randomaccount, "numofposts": "100", "findfollowers": true, "followersammount": 100, "comments": "comments.txt", "delay": "5,9" }

I tried the same parameters on a user. It seems to be working. It find the max amount of followers you specified, and visits every profile and leaves a comment on the posts it found ( < numofposts). Also, I see that the number of accounts you specified is way too high and might get you blocked temporarily (softban). Currently, there isn't a softban limit setting for the script but it will be added soon.
Please share a log like the one below (remove the usernames if you want).

[*] => Script started
[*] => Downloading webdriver for your version of Chrome
[*] => Loading Instagram
[*] => Delay: 5-9 secs
[*] => Attempting to log in with myinstausername
[*] => 2 factor authentication active. Enter your authentication code to continue
[*] => [Attempt# 1] Validating login
[*] => Login successful
[*] => Setting target to: someuser
[*] => Opening target sometarget
[*] => [open_target]: Attempt - 1
[*] => Finding followers of opensea
[*] => Restricting followers search to: 100
[*] => Opening followers list
[*] => Getting updated list of username divs
[*] => StaleElementReferenceException exception occured while capturing username links
[*] => Capturing div containing followers' list
[*] => Processing userdiv range: 0 - 87
[*] => Total username count: 50
[*] => Scrolling
[*] => Getting updated list of username divs
[*] => Scrolling
[*] => Scrolling
[*] => Scrolling
[*] => Scrolling
[*] => Scrolling
[*] => Processing userdiv range: 87 - 87
[*] => Total username count: 50
[*] => Scrolling
[*] => ['user1', 'user2',...]
[*] => Found 50 followers
[*] => Setting target to: someuser
[*] => [target: someuser] Opening target
[*] => [open_target]: Attempt - 1
[*] => [is_private]: text=>(This account is private) not found
[*] => [is_private]: text=>(This Account is private) not found
[*] => [is_private] text=>(This Account is Private) found.
[*] => [target: someuser] Private account
[*] => [target: someuser] No. of posts found: 0
[*] => [target: someuser] No posts found for the target
[*] => Setting target to: someuser
[*] => [target: someuser] Opening target
[*] => [open_target]: Attempt - 1
[*] => [is_private]: text=>(This account is private) not found
[*] => [is_private]: text=>(This Account is private) not found
[*] => [is_private]: text=>(This Account is Private) not found
[*] => [target: someuser] No. of posts found: 1
[*] => [target: someuser] Opening first post
[*] => [target: someuser] Number of posts to like: 1
[*] => [target: someuser] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [target: someuser] Comment disabled? No
[*] => [target: someuser] Commenting on the post
[*] => [comment]: Attempt - 1
[*] => [comment]: Attempt - 2
[*] => [target: someuser] Commented: Sheeeeeeesh!
[*] => [target: someuser] Moving on to the next post
[*] => [target: someuser] Waiting for 8 seconds
[*] => Setting target to: someuser
[*] => [target: someuser] Opening target
[*] => [open_target]: Attempt - 1
[*] => [is_private]: text=>(This account is private) not found
[*] => [is_private]: text=>(This Account is private) not found
[*] => [is_private] text=>(This Account is Private) found.
[*] => [target: someuser] Private account
[*] => [target: someuser] No. of posts found: 0
[*] => [target: someuser] No posts found for the target
[*] => Setting target to: someuser
[*] => [target: someuser] Opening target
[*] => [open_target]: Attempt - 1
[*] => [is_private]: text=>(This account is private) not found
[*] => [is_private]: text=>(This Account is private) not found
[*] => [is_private]: text=>(This Account is Private) not found
[*] => [target: someuser] No. of posts found: 3
[*] => [target: someuser] Opening first post
[*] => [target: someuser] Number of posts to like: 3
[*] => [target: someuser] Liking post: 1
[*] => [like]: Attempt - 1
[*] => [target: someuser] Comment disabled? No
[*] => [target: someuser] Commenting on the post
[*] => [comment]: Attempt - 1
[*] => [comment]: Attempt - 2
[*] => [target: someuser] Commented: Sheeeeeeesh!
[*] => [target: someuser] Moving on to the next post
[*] => [target: someuser] Waiting for 9 seconds
[*] => [target: someuser] Liking post: 2
