### ISSUE TITLE
Ignore list ignores everything

### ISSUE THREAD

**Issue by digitizesuccess** [shine-jayakumar/insta-likecom-bot#84]
As the title says, I was experimenting with an ignore list and added some spam tags to experiment with this new function.  It skipped everything as an irrelevant post. What am I doing wrong here? The posts it was skipping and marking irrelevant didn't have any of these tags in them. I've listed the tags from my list. 

#explorepage
#likeforlikes
#likeforlike
#memes
#spamforspam
#likes
#likeforfollow
#trending

**Comment by shine-jayakumar** [comment]
@digitizesuccess the issue is fixed. Please clone the latest push and let me know if you have any issues.

**Comment by shine-jayakumar** [comment]
If you want certain tags to not appear in the post, place those tags in a file (one tag per line), and use --ignoretags or -it parameter.

Sample file with tags to ignore:

```
#explorepage
#likeforlikes
#likeforlike
#memes
#spamforspam
#likes
#likeforfollow
#trending
```
then 
ilcbot.py -u username -p password -t '#sometarget' -ig ignoretags.txt

**Comment by digitizesuccess** [comment]
its working well. Thanks.
