### ISSUE TITLE
cannot locate element to like post or comment 

### ISSUE THREAD

**Issue by digitizesuccess** [shine-jayakumar/insta-likecom-bot#88]
I cloned the newest version and the issue is still persisting.

_Originally posted by @digitizesuccess in https://github.com/shine-jayakumar/insta-likecom-bot/issues/87#issuecomment-1688580043_

**Comment by shine-jayakumar** [comment]
Please share the logs because I am running the same version and it's working.

**Comment by digitizesuccess** [comment]
any updates?

**Comment by shine-jayakumar** [comment]
v.3.0.4 out. Please check if the problem persists.
