### ISSUE TITLE
Cannot find posts for tag targets v3.0.3

### ISSUE THREAD

**Issue by digitizesuccess** [shine-jayakumar/insta-likecom-bot#90]
It logs in and navigates to the hashtag target page but cannot find any posts and logs out. 

[*] => Login successful
[*] => Setting target to: #denver
[*] => [target: #denver] Opening target
[*] => [open_target]: Attempt - 1
[*] => [is_private]: text=>(This account is private) not found
[*] => [is_private]: text=>(This Account is private) not found
[*] => [is_private]: text=>(This Account is Private) not found
[*] => [target: #denverfoodie, retry=1] Unable to find posts. Reloading the target
[*] => [open_target]: Attempt - 1
^C[*] => [target: #denver, retry=2] Unable to find posts. Reloading the target
[*] => [open_target]: Attempt - 1
[*] => [open_target]: Attempt - 2
[*] => [open_target]: Attempt - 3
[*] => [open_target]: Attempt - 4
[*] => [target: #denver, retry=3] Unable to find posts. Reloading the target
[*] => [open_target]: Attempt - 1
[*] => [open_target]: Attempt - 2
[*] => [open_target]: Attempt - 3
[*] => [open_target]: Attempt - 4
[*] => [target: #denver] No posts found for the target
[*] => Script finished successfully
[*] => Total accounts: 1
[*] => Total post likes: 0
[*] => Total post comments: 0
[*] => Total post comment likes: 0
[*] => Total stories: 0
[*] => Total story likes: 0
[*] => Total story comments: 0
[*] => Total time taken: 62.3808 seconds

**Comment by williamgawysiak** [comment]
same
